package com.example.administrator.kotlintest.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.example.administrator.kotlintest.entity.date.AreaSelectedHistoryData;
import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "AREA_SELECTED_HISTORY_DATA".
*/
public class AreaSelectedHistoryDataDao extends AbstractDao<AreaSelectedHistoryData, Long> {

    public static final String TABLENAME = "AREA_SELECTED_HISTORY_DATA";

    /**
     * Properties of entity AreaSelectedHistoryData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CityId = new Property(1, int.class, "cityId", false, "CITY_ID");
        public final static Property WareHouserId = new Property(2, int.class, "wareHouserId", false, "WARE_HOUSER_ID");
        public final static Property Code = new Property(3, String.class, "code", false, "CODE");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property InsertTime = new Property(5, Long.class, "insertTime", false, "INSERT_TIME");
    }


    public AreaSelectedHistoryDataDao(DaoConfig config) {
        super(config);
    }
    
    public AreaSelectedHistoryDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AREA_SELECTED_HISTORY_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CITY_ID\" INTEGER NOT NULL ," + // 1: cityId
                "\"WARE_HOUSER_ID\" INTEGER NOT NULL ," + // 2: wareHouserId
                "\"CODE\" TEXT," + // 3: code
                "\"NAME\" TEXT," + // 4: name
                "\"INSERT_TIME\" INTEGER);"); // 5: insertTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AREA_SELECTED_HISTORY_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AreaSelectedHistoryData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCityId());
        stmt.bindLong(3, entity.getWareHouserId());
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(4, code);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        Long insertTime = entity.getInsertTime();
        if (insertTime != null) {
            stmt.bindLong(6, insertTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AreaSelectedHistoryData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCityId());
        stmt.bindLong(3, entity.getWareHouserId());
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(4, code);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        Long insertTime = entity.getInsertTime();
        if (insertTime != null) {
            stmt.bindLong(6, insertTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AreaSelectedHistoryData readEntity(Cursor cursor, int offset) {
        AreaSelectedHistoryData entity = new AreaSelectedHistoryData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // cityId
            cursor.getInt(offset + 2), // wareHouserId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // code
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // insertTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AreaSelectedHistoryData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCityId(cursor.getInt(offset + 1));
        entity.setWareHouserId(cursor.getInt(offset + 2));
        entity.setCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setInsertTime(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AreaSelectedHistoryData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AreaSelectedHistoryData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AreaSelectedHistoryData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
