package com.example.administrator.kotlintest.dao;

import com.example.administrator.kotlintest.bridge.retrofit.callback.CookieResulte;
import com.example.administrator.kotlintest.entity.date.AccountData;
import com.example.administrator.kotlintest.entity.date.AreaSelectedHistoryData;
import com.example.administrator.kotlintest.entity.date.SearchHistory;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cookieResulteDaoConfig;
    private final DaoConfig accountDataDaoConfig;
    private final DaoConfig areaSelectedHistoryDataDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;

    private final CookieResulteDao cookieResulteDao;
    private final AccountDataDao accountDataDao;
    private final AreaSelectedHistoryDataDao areaSelectedHistoryDataDao;
    private final SearchHistoryDao searchHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cookieResulteDaoConfig = daoConfigMap.get(CookieResulteDao.class).clone();
        cookieResulteDaoConfig.initIdentityScope(type);

        accountDataDaoConfig = daoConfigMap.get(AccountDataDao.class).clone();
        accountDataDaoConfig.initIdentityScope(type);

        areaSelectedHistoryDataDaoConfig = daoConfigMap.get(AreaSelectedHistoryDataDao.class).clone();
        areaSelectedHistoryDataDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        cookieResulteDao = new CookieResulteDao(cookieResulteDaoConfig, this);
        accountDataDao = new AccountDataDao(accountDataDaoConfig, this);
        areaSelectedHistoryDataDao = new AreaSelectedHistoryDataDao(areaSelectedHistoryDataDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);

        registerDao(CookieResulte.class, cookieResulteDao);
        registerDao(AccountData.class, accountDataDao);
        registerDao(AreaSelectedHistoryData.class, areaSelectedHistoryDataDao);
        registerDao(SearchHistory.class, searchHistoryDao);
    }
    
    public void clear() {
        cookieResulteDaoConfig.clearIdentityScope();
        accountDataDaoConfig.clearIdentityScope();
        areaSelectedHistoryDataDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
    }

    public CookieResulteDao getCookieResulteDao() {
        return cookieResulteDao;
    }

    public AccountDataDao getAccountDataDao() {
        return accountDataDao;
    }

    public AreaSelectedHistoryDataDao getAreaSelectedHistoryDataDao() {
        return areaSelectedHistoryDataDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

}
